yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
# from django.views.decorators.cache import cache_page

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('group/<slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': ('What would you like to say?'),
            'group': ('Does this post refer to any group from the list?')
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core.exceptions import PermissionDenied

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import paginator


def index(request):
    '''
    Направит на шаблон 'posts/index.html' с паджинатором
    по всем постам в базе данных.
    '''
    post_list = Post.objects.select_related('author', 'group')
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    '''
    Направит на шаблон 'posts/group_list.html' с паджинатором
    по всем постам группы group_id=slug и объектом этой группы.
    '''
    group_object = get_object_or_404(Group, slug=slug)
    post_list = group_object.posts.select_related('author').all()
    page_obj = paginator(request, post_list)
    context = {
        'group': group_object,
        'page_obj': page_obj,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    '''
    Направит на шаблон 'posts/profile.html' с паджинатором
    по всем постам автора username и объектом этого автора.
    '''
    author_object = get_object_or_404(User, username=username)
    post_list = author_object.posts.select_related(
        'group', 'author').all()
    page_obj = paginator(request, post_list)
    following = None
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user,
                                          author=author_object)
    context = {
        'page_obj': page_obj,
        'author_object': author_object,
        'following': following
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    '''
    Направит на шаблон 'posts/post_detail.html' поста с id=post_id
    с объектом этого поста.
    '''
    post_object = get_object_or_404(Post.objects.select_related(
        'group', 'author'), pk=post_id)
    comments = post_object.comments.all()
    if post_object is None:
        raise Http404("Post does not exist")
    count = post_object.author.posts.count()
    form = CommentForm(request.POST or None)
    context = {
        'post': post_object,
        'count': count,
        'comments': comments,
        'form': form
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    '''
    Направит на шаблон 'posts/create_post.html' создания поста,
    при отправке валидной формы методом POST создаст пост от автора, из
    логина которого совершается отправка формы.
    '''
    form = PostForm(request.POST or None,
                    files=request.FILES or None)

    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    context = {
        'form': form
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    '''
    Направит на шаблон 'posts/create_post.html' редактирования поста, с
    заполненной формой оригинальным содержанием поста post_id,
    при отправки валидной формы методом POST изменит пост от автора, из
    логина которого совершается отправка формы.
    '''
    is_edit = True
    post_object = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post_object)
    if request.user != post_object.author:
        raise PermissionDenied
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': is_edit
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    '''
    Добавит комментарий к посту при отправке валидной формы ПОСТ и
    перенаправит на страницу post_detail.
    '''
    post_object = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post_object
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    '''
    Покажет страницу с записями авторов, на которых подписан пользователь.
    '''
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    '''
    Добавит подписку пользователя на автора, путем добавления записи в
    базе данных.
    '''
    author_object = get_object_or_404(User, username=username)
    if request.user == author_object \
            or Follow.objects.filter(user=request.user,
                                     author=author_object).exists():
        return redirect('posts:follow_index')
    new_follow = Follow(user=request.user, author=author_object)
    new_follow.save()
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    '''
    Удалит подписку пользователя на автора, путем удаления записи в
    базе данных.
    '''
    author_object = get_object_or_404(User, username=username)
    unfollow = Follow.objects.filter(user=request.user, author=author_object)
    if unfollow:
        unfollow.delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
{% endblock %}

{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
            </div>
            <div class="card-body">
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'posts/includes/form.html' %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
  Ваши подписки
{% endblock %}

{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/posts.html' %} 
    {% if post.group %}   
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a><br>
    {% endif %}
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Записи сообщества {{ group }}
{% endblock %}

{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'includes/posts.html' %} 
    <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a><br>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% load cache %}
{%  block content %}
  {% cache 20 index_page %}
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/posts.html' %} 
      {% if post.group %}   
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a><br>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  {% endcache %} 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Пост {{ post.text|truncatewords:30 }}
{% endblock %}

{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y"  }}
          </li>
          {% if post.group %}   
            <li class="list-group-item">Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.username}}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "500x100" crop="center" upscale=False as im %}
          <img class="card-img my-2" style="width:500px" src="{{ im.url }}">
        {% endthumbnail %}<br>
        <p>
          {{ post.text }}
        </p>
        {% comment %} {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %} {% endcomment %}
        {% if post.author.pk == request.user.pk %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>   
        {% endif %}
        {% include 'posts/includes/comment.html' %}
      </article>
    </div> 
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author_object.get_full_name }}
{% endblock %}

{% block content %}  
  <class="container py-5">        
    <h1>Все посты пользователя {{ author_object.get_full_name }} </h1>
    <h3>Всего постов: {{ author_object.posts.count }} </h3>       
    {% for post in page_obj %}
      {% include 'includes/posts.html' %} 
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a><br>
      {% if post.group %}   
        <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %} 
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author_object %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author_object %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
  </div>
{% endblock %}
     