yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView, LogoutView, LoginView,
    PasswordResetView, PasswordResetCompleteView,
    PasswordChangeView, PasswordResetConfirmView
)
from django.views.generic import TemplateView
from django.urls import path, reverse_lazy

from . import views


app_name = 'users'


urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/', LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')),
        name='password_change_form'
    ),
    path(
        'password_change_done/',
        TemplateView.as_view(
            template_name="users/password_change_done.html"),
        name="password_change_done"
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"),
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"),
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"),
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/models.py
# from django.db import models

# # Create your models here.

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title%}<title>Вы вышли из системы</title>{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/login.html
{% extends "user_password_forms.html" %}

{% block title %}<title>Войти</title>{% endblock %}

{% block name %}
  Войти на сайт 
{% endblock %}

{% block button %}
  <button type="submit" class="btn btn-primary">  
    Войти 
  </button> 
  <a href="{% url 'users:password_reset' %}" class="btn btn-link">  
    Забыли пароль?  
  </a>  
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "user_password_info.html" %}

{% block title %}<title>Пароль изменён</title>{% endblock %}

{% block name %}
  Пароль изменён
{% endblock %}

{% block body %}
  <p>Пароль изменён успешно</p>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "user_password_forms.html" %}

{% block title %}<title>Изменение пароля</title>{% endblock %}

{% block name %}
  Изменить пароль
{% endblock %}

{% block button %}
  <button type="submit" class="btn btn-primary">
    Изменить пароль
  </button>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "user_password_info.html" %}

{% block title %}<title>Сброс пароля прошёл успешно</title>{% endblock %}

{% block name %}
  Восстановление пароля завершено
{% endblock %}

{% block body %}
  <p>Ваш пароль был сохранен. Используйте его для входа</p>
  <a href="{% url 'users:login' %}">войти</a>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "user_password_forms.html" %}

{% block title %}<title>Новый пароль</title>{% endblock %}

{% block name %}
  Введите новый пароль
{% endblock %}

{% block button %}
  <button type="submit" class="btn btn-primary">
    Назначить новый пароль
  </button>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "user_password_info.html" %}

{% block title %}<title>Сброс пароля прошёл успешно</title>{% endblock %}

{% block name %}
  Отправлено письмо
{% endblock %}

{% block body %}
  Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "user_password_forms.html" %}

{% block title %}<title>Сброс пароля</title>{% endblock %}

{% block name %}
  Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
{% endblock %}

{% block button %}
  <button type="submit" class="btn btn-primary">
    Сбросить пароль
  </button>
{% endblock %}
            

yatube/templates/users/signup.html
{% extends "user_password_forms.html" %}

{% block title %}<title>Зарегистрироваться</title>{% endblock %}

{% block name %}
  Зарегистрироваться
{% endblock %}

{% block button %}
  <button type="submit" class="btn btn-primary">
    Зарегистрироваться
  </button>
{% endblock %}